### ISSUE TITLE
Support from_attribute similar to Panel widgets .from_param

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#4]
With Panel you can ([see](https://panel.holoviz.org/user_guide/Param.html#custom-widgets))

```python
widget = pn.widgets.IntSlider.from_param(Example.param.unbounded_int, start=0, end=100)
```

Being able to create single widgets from Pydantic Model Attributes would be very useful as well. Some method like the below would be useful

```python
widget = from_attribute(pn.widgets.IntSlider, example, "unbounded", start=0, end=100)
```

**Comment by jmosbacher** [comment]
Im not sure I understand what you are proposing. Do you mean to split up the logic inside the for loop of [pydantic_widgets](https://github.com/jmosbacher/pydantic-panel/blob/5dcd3162355475e6d9f2fa72faf1fe82f8189493/pydantic_panel/widgets.py#L35) to a separate function so people can use the function to get a single widget instead of a dictionary with widgets for each field? Or do mean to just make this function more accessible to users that want to create the widgets and modify them themselves?

**Comment by MarcSkovMadsen** [comment]
I actually don't understand the implementation of `pydantic-panel` yet. But what I propose is to expose functionality to create a single widget.

The motivation is that I have often seen with `Param` that users ask for help to define or get hold of single widgets.

**Comment by jmosbacher** [comment]
Ok, I guess I can add documentation for how to do this and maybe some more user friendly docstrings. Currently this function is just used internally.

**Comment by jmosbacher** [comment]
This is now solved via Pydantic pane supporting arbitrary python objects.
e.g. for the above example `pn.panel(example, start=0, end=100)` works.
